// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw0hFCqpt83wirMwMlc0o30FeApwircj0',
    appId: '1:894739389977:web:2803271f2f7d6b6c175488',
    messagingSenderId: '894739389977',
    projectId: 'guavafinance-7d405',
    authDomain: 'guavafinance-7d405.firebaseapp.com',
    storageBucket: 'guavafinance-7d405.firebasestorage.app',
    measurementId: 'G-3RZJ0KESR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfRMiWVPqkK5SpGqEetVgsG6nRN3iwSBk',
    appId: '1:894739389977:android:711c14dbba0c615e175488',
    messagingSenderId: '894739389977',
    projectId: 'guavafinance-7d405',
    storageBucket: 'guavafinance-7d405.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwyBt32MyTra5t69KLETSj2LiLZ7wDeYs',
    appId: '1:894739389977:ios:e643f154b5784b32175488',
    messagingSenderId: '894739389977',
    projectId: 'guavafinance-7d405',
    storageBucket: 'guavafinance-7d405.firebasestorage.app',
    iosBundleId: 'finance.guava',
  );

}